### PR TITLE
[FLINK-33970] Add necessary checks for connector document

### PR DESCRIPTION
**Pull request by GOODBOY008**
Add dead link check for connector document.

### CODE REVIEW

**Comment by GOODBOY008** [comment]
@leonardBang @tisonkun  PTAL. Currently, I just add simple scripts to check dead link instead of use hugo to build doc.

**Comment by tisonkun** [comment]
CI broken. PTAL.

**Comment by GOODBOY008** [comment]
> CI broken. PTAL.

I had rebase to latest master.

**Review by tisonkun — APPROVED** [review]
Thank you!

**Comment by tisonkun** [comment]
Now we can pick this patch to v4.1 >_<

**Pull request merged**
