### PR TITLE
[FLINK-33400] Be Compatible with Flink 1.18

### PR DESCRIPTION
**Pull request by tisonkun**
## Purpose of the change

Be sure 1.18 compatibility

## Brief change log

- *Change the internal design of `ProducerRegister`.*
- *Expose topic metadata query in `PulsarSinkContext`.*
- *Change the internal metadata cache in `MetadataListener`.*

## Verifying this change

Existing tests should pass.

## Significant changes

*(Please check any boxes [x] if the answer is "yes". You can first publish the PR and check them afterwards, for
convenience.)*

- [ ] Dependencies have been added or upgraded
- [ ] Public API has been changed (Public API is any class annotated with `@Public(Evolving)`)
- [ ] Serializers have been changed
- [ ] New feature has been introduced
    - If yes, how is this documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by tisonkun** [comment]
image

@leonardBang @zentol @MartijnVisser how can I overcome this false positive violations .. It seems upstream changes the text literal and I cannot pass both 1.17 and 1.18 (either has a distinct text format)

**Comment by tisonkun** [comment]
It seems refreeze + duplicate helps.

**Review by leonardBang — APPROVED** [review]
Thanks @tisonkun for the contribution, LGTM

**Comment by leonardBang** [comment]
I've discussed offline with @tisonkun, we can skip the arch rule for junit5 check temporarily as it's not a blocker for release, and then we should can migrate these tests to junit5 to satisfy the Arch Rule in connector repos.

**Pull request merged**
