### PR TITLE
[FLINK-24302][Connector/Pulsar] Drop the use of direct buffer memory for supporting Java 11.

### PR DESCRIPTION
**Pull request by syhily**
This is working in progress PR for testing if we have supported Java 11 by changing the Netty allocator type to heap instead of direct buffer memory.

### CODE REVIEW

**Comment by cbornet** [comment]
Is this still needed now that Pulsar 2.11 client is used ?

**Comment by syhily** [comment]
> Is this still needed now that Pulsar 2.11 client is used ?

Yep. The main issue still doesn't be resolved after Pulsar has released the 3.0.0

**Comment by tisonkun** [comment]
@syhily is there an issue or related PRs in the Pulsar side to describe why we have to do these tricks in the connector side?

**Comment by syhily** [comment]
> @syhily is there an issue or related PRs in the Pulsar side to describe why we have to do these tricks in the connector side?

Yep. Here it is. https://github.com/apache/pulsar/issues/17989

**Comment by syhily** [comment]
Close this PR for in favor of the #55.

**Pull request closed without merging**
