### PR TITLE
[BK-3.0][FLINK-30552][Connector/Pulsar] drop batch message size assertion, better set the cursor position.

### PR DESCRIPTION
**Pull request by syhily**
This is a backport PR for #11.

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
Thanks for taking care of this.

Merging..

**Comment by a11enhuang** [comment]
Is there any plan to release this version? The currently used `Flink 1.16` version often receives an error: `We only support normal message id currently. This batch size is %d`

**Comment by robertstef116** [comment]
@tisonkun @syhily I also still seeing this issue in ```Flink 1.16.1```. When this fix is planned to be released?

**Comment by nikolasten** [comment]
Same here when is the plan to release this?

**Comment by syhily** [comment]
@MartijnVisser we may need a new 4.0 release.

**Comment by nikolasten** [comment]
Is there a way to use latest snapshot version instead of waiting for a release of this? In which repo is snapshot version published?
We are having production issues due to this. Pipeline fails to recover from checkpoint when batch id is stored in checkpoint.

**Comment by nikolasten** [comment]
Disregard my latest comment. 
When used with flink 1.17 works fine.

If anybody else has a problem and waiting for release, we used snapshot version with flink 1.17.

```gradle 
maven {
        url "https://repository.apache.org/content/repositories/snapshots"
}
implementation "org.apache.flink:flink-connector-pulsar:4.0-20230404.065406-2"

**Comment by MartijnVisser** [comment]
> @MartijnVisser we may need a new 4.0 release.

@syhily @tisonkun I'll create a 4.0 release candidate today

**Comment by tisonkun** [comment]
@MartijnVisser What do you think of https://issues.apache.org/jira/browse/FLINK-31748? I left a comment at https://issues.apache.org/jira/browse/FLINK-25509?focusedCommentId=17708825&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17708825 to understand whether it's a blocker and how we handle version matrix (especially nightly workflow keep failing) but no response yet.

**Comment by tisonkun** [comment]
I see the respond. Feel free to cc me to verify the release. I'll send a patch to suppress the compile issue but still wait a bit for @syhily to implement FLINK-31748.

**Comment by minchowang** [comment]
@syhily Hi, Whether can apply to develop-1.14 [develop-flink-1.14](https://github.com/streamnative/flink/tree/develop) for this PR.

**Pull request merged**
