### PR TITLE
[FLINK-30606][Connector/Pulsar] Bump the pulsar-client-all to latest 2.11.0.

### PR DESCRIPTION
**Pull request by syhily**
This is a PR for bumping the `pulsar-client-all` to latest 2.11.0.

### CODE REVIEW

**Comment by syhily** [comment]
This PR is completed on top of #24, we will rebase it until the #24 is merged.

**Comment by syhily** [comment]
```
2023-02-12T12:00:08.6685939Z [10.449s][error][gc] Failed to commit memory (Not enough space)
2023-02-12T12:00:08.6686284Z [19.855s][error][gc] Forced to lower max Java heap size from 2048M(100%) to 2046M(100%)
2023-02-12T12:00:08.6686711Z [19.855s][error][gc] Failed to allocate initial Java heap (2048M)
2023-02-12T12:00:08.6687024Z Error: Could not create the Java Virtual Machine.
2023-02-12T12:00:08.6688159Z Error: A fatal exception has occurred. Program will exit.
```

@tisonkun @MartijnVisser Any ideas on this? The new Pulsar docker instance may require more memory than the limit?

**Comment by MartijnVisser** [comment]
> @MartijnVisser Any ideas on this? The new Pulsar docker instance running in JDK 17 may require more memory than the limit?

Flink doesn't support Java 17 so I'm not sure how this would work.

**Review by tisonkun — APPROVED** [review]
Thanks for your contribution @syhily! Great work XD.

Merging...

**Pull request merged**
