### PR TITLE
[FLINK-33884] Update Pulsar dependency to 3.0.2 in Pulsar Connector

### PR DESCRIPTION
**Pull request by dchristle**
## Purpose of the change

Update the Pulsar dependency version to pick up patch fixes.

## Brief change log

- Update `pulsar.version` to `3.0.2` in pom.xml.

## Verifying this change

This change added tests and can be verified as follows:

- Manually verified by running the Pulsar connector on a local Flink cluster.

Running this on a production workload did not uncover any issues.

## Significant changes

*(Please check any boxes [x] if the answer is "yes". You can first publish the PR and check them afterwards, for
convenience.)*

- [x] Dependencies have been added or upgraded
- [ ] Public API has been changed (Public API is any class annotated with `@Public(Evolving)`)
- [ ] Serializers have been changed
- [ ] New feature has been introduced
    - If yes, how is this documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by syhily** [comment]
The license file version should also be bumped in the mean time.

**Comment by MartijnVisser** [comment]
@dchristle I've triggered the CI, but I'm expecting that upgrading the version will also have impact on the license checks (the listed versions in the NOTICE files)

**Comment by dchristle** [comment]
> @dchristle I've triggered the CI, but I'm expecting that upgrading the version will also have impact on the license checks (the listed versions in the NOTICE files)

Got it. Yes, I see the CI check for the NOTICE file failed due to out-of-date info. I updated the dependency versions in the META-INF NOTICE file. I also updated the year to 2024, in case that could also prevent the CI check from passing. We can bump the year in a separate hotfix PR, if you'd prefer, as well.

**Comment by syhily** [comment]
Thanks, there are no issues from my side. @tisonkun Can you help me double check this PR?

**Review by tisonkun — APPROVED** [review]

**Pull request merged**
