### PR TITLE
[FLINK-33964][pulsar][docs] Remove dead link

### PR DESCRIPTION
**Pull request by GOODBOY008**
Remove dead link.

### CODE REVIEW

**Comment by GOODBOY008** [comment]
@tisonkun PTAL

**Review by tisonkun — APPROVED** [review]
Thank you! I'd appreciated it if you can backport to v4.1 branch also.

**Comment by GOODBOY008** [comment]
> Thank you! I'd appreciated it if you can backport to v4.1 branch also.

@tisonkun Big thanks for your quick review. I want to add document check for connector document https://github.com/apache/flink-connector-pulsar/pull/78, Can you help me to review it?

**Comment by GOODBOY008** [comment]
@leonardBang PTAL

**Pull request merged**
