### PR TITLE
[FLINK-32003] Upgrade pulsar-client version to work with OAuth2

### PR DESCRIPTION
**Pull request by tisonkun**
## Purpose of the change

Upgrade pulsar-client version to work with OAuth2

## Verifying this change

Existing tests should pass.

## Significant changes

*(Please check any boxes [x] if the answer is "yes". You can first publish the PR and check them afterwards, for
convenience.)*

- [x] Dependencies have been added or upgraded
- [ ] Public API has been changed (Public API is any class annotated with `@Public(Evolving)`)
- [ ] Serializers have been changed
- [ ] New feature has been introduced
    - If yes, how is this documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by nlu90 — APPROVED** [review]

**Comment by tisonkun** [comment]
@nlu90 No luck - Pulsar patch release breaks interface:

```
Error:  COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
Error:  /home/runner/work/flink-connector-pulsar/flink-connector-pulsar/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/schema/PulsarSchemaUtils.java:[184,16] no suitable constructor found for SchemaInfoImpl(java.lang.String,byte[],org.apache.pulsar.common.schema.SchemaType,java.util.Map<java.lang.String,java.lang.String>)
    constructor org.apache.pulsar.client.impl.schema.SchemaInfoImpl.SchemaInfoImpl(java.lang.String,byte[],org.apache.pulsar.common.schema.SchemaType,long,java.util.Map<java.lang.String,java.lang.String>) is not applicable
      (actual and formal argument lists differ in length)
    constructor org.apache.pulsar.client.impl.schema.SchemaInfoImpl.SchemaInfoImpl() is not applicable
      (actual and formal argument lists differ in length)
Error:  /home/runner/work/flink-connector-pulsar/flink-connector-pulsar/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/schema/PulsarSchema.java:[180,27] no suitable constructor found for SchemaInfoImpl(java.lang.String,byte[],org.apache.pulsar.common.schema.SchemaType,java.util.Map<java.lang.String,java.lang.String>)
    constructor org.apache.pulsar.client.impl.schema.SchemaInfoImpl.SchemaInfoImpl(java.lang.String,byte[],org.apache.pulsar.common.schema.SchemaType,long,java.util.Map<java.lang.String,java.lang.String>) is not applicable
      (actual and formal argument lists differ in length)
    constructor org.apache.pulsar.client.impl.schema.SchemaInfoImpl.SchemaInfoImpl() is not applicable
      (actual and formal argument lists differ in length)
```

**Comment by tisonkun** [comment]
Change to builder which is a compatible way - test compile from 2.10.1 to 2.10.4.

**Comment by reswqa** [comment]
It seems that we have some format violations.

**Comment by tisonkun** [comment]
Werid. I run already `mvn spotless:apply` and no diff report.

**Comment by tisonkun** [comment]
Emm...It seems that plugin is default to skip.

**Comment by reswqa** [comment]
> Werid. I run already mvn spotless:apply and no diff report.

Did you manually execute `mvn spotless: apply`, which successfully fixed the formatting issue on my mac.

**Comment by tisonkun** [comment]
@reswqa I manually disable skip. But the default config seems:

```
                        <plugin>
                            <groupId>com.diffplug.spotless</groupId>
                            <artifactId>spotless-maven-plugin</artifactId>
                            <configuration>
                                <skip>true</skip>
                            </configuration>
                        </plugin>
```

in `flink-connector-parent-1.0.pom`.

**Review by nlu90 — APPROVED** [review]

**Review by reswqa — APPROVED** [review]
Thanks @tisonkun.

**Comment by tisonkun** [comment]
Still a few breaking things.

I'm trying to pick https://github.com/apache/flink/pull/21204.

**Comment by tisonkun** [comment]
I'm feeling lucky now ;-)

**Comment by tisonkun** [comment]
Pending for merging...

Although, I suggest a release is required to deliver this fix to downstream users.

cc @MartijnVisser @leonardBang @dannycranmer what do you think and how can I help in release?

**Pull request merged**
