### PR TITLE
[FLINK-33964] Drop admin docs reference

### PR DESCRIPTION
**Pull request by tisonkun**
This fixes FLINK-33964.

### CODE REVIEW

**Comment by MartijnVisser** [comment]
I think this should (also) be pointed towards the release branch for the connector

**Comment by tisonkun** [comment]
@MartijnVisser if you mean backport to 4.1, I'll make one.

**Comment by leonardBang** [comment]
LOL, @tisonkun I just raised a PR at the same time

**Review by leonardBang — APPROVED** [review]
+1

**Pull request merged**
